apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: postgres
  newName: gcr.io/myproject/postgres
  newTag: v15.4.0-customtag

namespace: postgres
