apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

resources:
- ../../base

images:
- name: postgres
  newName: gcr.io/myproject/postgres
  newTag: v15.6.0-customtag
