name: 'Kustomize Build Action'

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'master', 'main', 'v0.2.1' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: tcarland/kustomize-build-action@v0.1.0
        with:
          kustomize_dir: './manifests'
